# Generated by Django 4.2.4 on 2023-09-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="LabelID",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label_id", models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ObjectDetectionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "category_labels",
                    models.ManyToManyField(
                        related_name="models", to="models.categorylabel"
                    ),
                ),
                (
                    "classes_during_inference",
                    models.ManyToManyField(
                        blank=True,
                        related_name="models_inference",
                        to="models.categorylabel",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="categorylabel",
            name="label_ids",
            field=models.ManyToManyField(
                related_name="category_labels", to="models.labelid"
            ),
        ),
    ]
