# Generated by Django 4.2.4 on 2023-09-07 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0003_objectdetectionmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="objectdetectionmodel",
            name="category_label",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="model",
                to="models.categorylabel",
            ),
        ),
        migrations.AddField(
            model_name="objectdetectionmodel",
            name="classes_during_inference",
            field=models.ManyToManyField(
                blank=True, related_name="models_inference", to="models.categorylabel"
            ),
        ),
    ]
