# Generated by Django 4.2.4 on 2023-09-07 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0004_objectdetectionmodel_category_label_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objectdetectionmodel",
            name="category_label",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="model",
                to="models.categorylabel",
            ),
        ),
    ]
