# Generated by Django 4.2.4 on 2023-09-07 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0005_alter_objectdetectionmodel_category_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objectdetectionmodel",
            name="category_label",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="model",
                to="models.categorylabel",
            ),
        ),
    ]
