# Generated by Django 4.2.4 on 2023-09-08 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0006_alter_objectdetectionmodel_category_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objectdetectionmodel",
            name="category_label",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="model",
                to="models.categorylabel",
            ),
        ),
        migrations.AlterField(
            model_name="objectdetectionmodel",
            name="model_file",
            field=models.FileField(upload_to=""),
        ),
    ]
