# Generated by Django 4.2.4 on 2023-09-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_alter_profile_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="model_use_count",
            field=models.JSONField(default=dict),
        ),
    ]
