# Generated by Django 4.2.4 on 2023-09-07 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Image",
        ),
    ]
