# Generated by Django 4.2.4 on 2023-09-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_profile_model_use_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="age",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                max_length=1,
            ),
        ),
    ]
